---

- name: Fail if os family is not redhat or debian
  fail:
    msg: Current role does not support on {{ ansible_os_family | lower }}, It only supports CentOS/RedHat and Debian hosts.
  when: (ansible_os_family | lower) not in ['redhat', 'debian']

- name: validate vars
  include_tasks: tasks/variables.yml

- name: prerequisite
  include_tasks: "tasks/{{ ansible_os_family | lower }}-prerequisite.yml"

- name: install
  include_tasks: "tasks/linux-install.yml"
  when: state|default('present') == 'present'

- name: clear temp folder
  include_tasks: "tasks/linux-clear-temp.yml"
  when: clear_temp_folder | default('no') | bool
  
- name: track versions
  include_tasks: "tasks/linux-track-versions.yml"
  when: state|default('present') == 'present'

- name: remove archived versions
  include_tasks: "tasks/linux-remove-archived.yml"
  when: state|default('present') == 'present'

- name: uninstall
  include_tasks: "tasks/linux-uninstall.yml"
  when: state|default('present') == 'absent'
