
- name: start the service
  systemd:
    state: started
    daemon_reload: yes
    name: "{{ service_name }}"
    enabled: yes
  become: yes

- name: wait for service to start
  health_check:
    url: "http://localhost:{{ health_check_port}}{{ health_check_uri | default('/manage/info') }}"
    expected_status: "{{ health_check_status | default('200') }}"
    max_retries: "{{ health_check_max_retries | default('60') }}"

- name: get installed version
  uri:
    url: "http://localhost:{{ health_check_port}}{{ health_check_uri_ver | default('/manage/info') }}"
    return_content: yes
  register: api_response

- name: print installed version
  debug:
    msg: " Installed version: {{ api_response.content.build.version }}"

- name: print finish
  debug:
    msg: "finish"

# Do once can get version from somewhere

# - name: get installed version from version.properties file
#   slurp:
#     src: "{{ installation_folder }}/conf/version.properties"
#   register: installed_version
  
# - name: print installed version
#   debug:
#     msg: " Installed version: {{ (installed_version['content'] | b64decode).split('=')[1] }}"

# - name: fail if app_version is not equal to installed version
#   fail:
#     msg: "app_version: {{ app_version }} does not macthed to installed version {{ (installed_version['content'] | b64decode).split('=')[1] }}"
#   when: app_version != (installed_version['content'] | b64decode).split('=')[1]
  